<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_content
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (JLanguageAssociations::isEnabled() && $params->get('show_associations'));
JHtml::_('behavior.caption');

?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if ($this->params->get('show_page_heading')) : ?>
	<div class="page-header heading">
		<h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
	</div>
	<?php endif;
if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
{
	echo $this->item->pagination;
}
?>

	<?php // Todo Not that elegant would be nice to group the params ?>
	<?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
	|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

	<?php if (!$useDefList && $this->print) : ?>
		<div id="pop-print" class="btn hidden-print">
			<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
		</div>
		<div class="clearfix"> </div>
	<?php endif; ?>
	<?php if ($params->get('show_title') || $params->get('show_author')) : ?>
	<div class="page-header">

	<?php if ($this->params->get('show_page_heading')) : ?>		
		<h2 itemprop="headline">
			<?php if ($params->get('show_title')) : ?>
				<?php echo $this->escape($this->item->title); ?>
			<?php endif; ?>
		</h2>
	<?php endif; ?>
	<?php if (!$this->params->get('show_page_heading')) : ?>		
		<h1 itemprop="name">
			<?php if ($params->get('show_title')) : ?>
					<?php echo $this->escape($this->item->title); ?>
				<?php endif; ?>
		</h1>
			<?php endif; ?>
		<?php if ($this->item->state == 0) : ?>
			<span class="label label-warning"><?php echo JText::_('JUNPUBLISHED'); ?></span>
		<?php endif; ?>
		<?php if (strtotime($this->item->publish_up) > strtotime(JFactory::getDate())) : ?>
			<span class="label label-warning"><?php echo JText::_('JNOTPUBLISHEDYET'); ?></span>
		<?php endif; ?>
		<?php if ((strtotime($this->item->publish_down) < strtotime(JFactory::getDate())) && $this->item->publish_down != JFactory::getDbo()->getNullDate()) : ?>
			<span class="label label-warning"><?php echo JText::_('JEXPIRED'); ?></span>
		<?php endif; ?>
	</div>
	<?php endif; ?>
	<?php if (!$this->print) : ?>
		<?php if ($canEdit || $params->get('show_print_icon') || $params->get('show_email_icon')) : ?>
			<?php echo JLayoutHelper::render('joomla.content.icons', array('params' => $params, 'item' => $this->item, 'print' => false)); ?>
		<?php endif; ?>
	<?php else : ?>
		<?php if ($useDefList) : ?>
			<div id="pop-print" class="btn hidden-print">
				<?php echo JHtml::_('icon.print_screen', $this->item, $params); ?>
			</div>
		<?php endif; ?>
	<?php endif; ?>

	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php echo $this->item->event->afterDisplayTitle; ?>

	<?php if ($useDefList && ($info == 0 || $info == 2)) : ?>
		<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
		<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'above')); ?>
	<?php endif; ?>

	<?php if ($info == 0 && $params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
		<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>

		<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
	<?php endif; ?>

<?php 
		// cambio jc 20140321 publicacion del metadato dcterms.issued para buscador.
		// @ variables: $row | $this->item | $this->article
		// @ atributos: modified | publish_up 
		// http://stackoverflow.com/questions/16171686/list-of-standard-w3c-meta-tags
		// https://docs.joomla.org/J3.x:Adding_JavaScript_and_CSS_to_the_page
	$mydocument = JFactory::getDocument();
	//$mytitle = $mydocument->getTitle();
	$mytitle = $this->item->title;
	$mylanguage = $mydocument->getLanguage();
	$current_lang = JFactory::getLanguage()->getTag();
	$organization = '';
	if (($current_lang == 'es-ES') || ($current_lang == 'fr-FR')) $organization = 'OPS/OMS';
	if (($current_lang == 'en-GB') || ($current_lang == 'en-US')) $organization = 'PAHO/WHO';
	if ($current_lang == 'pt-BR') $organization = 'OPAS/OMS';
	$mytitle_og =  $organization . " | " . $mytitle;
	$mydocument->setTitle( $mytitle_og );
	$mypubdate = $mydocument->getMetaData('DCTERMS.issued');
	if (($mypubdate == '0000-00-00 00:00:00') || ($mypubdate == '')) $mypubdate = $this->item->created;
	if ($mypubdate <= $this->item->publish_up) {
		$mypubdate=$this->item->publish_up;
		if (($mypubdate == '0000-00-00 00:00:00') || ($mypubdate == '')) $mypubdate = $this->item->publish_up;
		if (($mypubdate == '0000-00-00 00:00:00') || ($mypubdate == '')) $mypubdate = $this->item->created;
		$mydocument->setMetaData( 'DCTERMS.issued', $mypubdate );
		$date1 = date_create($mypubdate);
		$date2 = date_format($date1, 'Y-m-d');
		$mydocument->setMetaData( 'review_date', $date2 );
	}
	$mydescription = $mydocument->description;
	$lengthdescription = strlen($mydescription);
	if ($lengthdescription < 159) {
		$mydescription .= strip_tags ($this->item->text.". ");
		$mydescription = str_replace("&nbsp;", " ", $mydescription);
		$mydescription = str_replace("\r\n", " ", $mydescription);
		$mydescription = str_replace("\t", " ", $mydescription);
		$mydescription = str_replace("&amp;amp;", "&amp;", $mydescription);
		$mydescription = str_replace("  ", " ", $mydescription);
		$mydescription = str_replace("  ", " ", $mydescription);
		$mydescription = str_replace("  ", " ", $mydescription);
	}
	$desc = explode(' ', $mydescription);
	$desc = array_slice($desc, 0, 29);
	$mydescription = implode(" ", $desc);
	$mydescription = htmlentities($mydescription, ENT_COMPAT, "UTF-8");


$newogtagimages = "";
$newtwittertagimages = "";
if (isset($images->image_intro)) {
	$newogtagimages .= "	<link rel=\"image_src\" type=\"image/png\" href=\"".$images->image_intro."\" />
	<meta property=\"og:image\" content=\"".$images->image_intro."\" />
	<meta property=\"og:image:width\" content=\"300\" />
	<meta property=\"og:image:height\" content=\"300\" />
";
	$newtwittertagimages .= "  <meta name=\"twitter:image:src\" content=\"".$images->image_intro."\" />
";
} 


//	$mydescription = substr($mydescription,0,159) . "...";
	$mydocument->setMetaData( 'description', $mydescription );
	$newogtag = "<meta property=\"og:title\" content=\"".$mytitle_og."\" />
	<meta property=\"og:site_name\" content=\"Pan American Health Organization / World Health Organization\"/>
	<meta property=\"og:type\" content=\"article\" />
	<meta property=\"og:description\" content=\"".$mydocument->description."\" />
	";
	$newtwittertag = "  <meta name=\"twitter:title\" content=\"".$mytitle_og."\"/>
  <meta name=\"twitter:description\" content=\"".$mydescription."\" />

	";

	$newogtagimages_default = "<link rel=\"image_src\" type=\"image/png\" href=\"http://www.paho.org/hq/images/logo-ops.png\" />
	<meta property=\"og:image\" content=\"http://www.paho.org/hq/images/logo-ops.png\" />
	<meta property=\"og:image:width\" content=\"800\" />
	<meta property=\"og:image:height\" content=\"750\" />
	<meta property=\"og:image\" content=\"http://www.paho.org/hq/images/logo-paho.png\" />
	<meta property=\"og:image:width\" content=\"800\" />
	<meta property=\"og:image:height\" content=\"750\" />
";
	$newtwittertagimages_default = "  <meta name=\"twitter:image:src\" content=\"http://www.paho.org/hq/images/logo-paho.png\" />
";
	if ($newogtagimages != "") {
		$newogtag .= $newogtagimages;
	}	else {
		$newogtag .= $newogtagimages_default;
	}
	$mydocument->addCustomTag( $newogtag );

	if ($newtwittertagimages != "") {
		$newtwittertag .= $newtwittertagimages;
	}	else {
		$newtwittertag .= $newtwittertagimages_default;
	}
	$mydocument->addCustomTag( $newtwittertag );
		// https://findmyfbid.com
		// default app. https://stackoverflow.com/questions/38541027/facebook-share-app-id-missing
	$fbid = "<meta property=\"fb:app_id\" content=\"1906460059619279\">
		<meta property=\"article:author\" content=\"https://www.facebook.com/pahowho\" />
		<meta property=\"author\" content=\"https://www.facebook.com/pahowho\" />
";
	$mydocument->addCustomTag( $fbid ); 
?>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>

	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php if ($params->get('access-view')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.full_image', $this->item); ?>
	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && !$this->item->paginationrelative) :
		echo $this->item->pagination;
	endif;
	?>
	<?php if (isset ($this->item->toc)) :
		echo $this->item->toc;
	endif; ?>
	<div itemprop="articleBody">
		<?php echo $this->item->text; ?>
	</div>

	<?php if ($info == 1 || $info == 2) : ?>
		<?php if ($useDefList) : ?>
				<?php // Todo: for Joomla4 joomla.content.info_block.block can be changed to joomla.content.info_block ?>
			<?php echo JLayoutHelper::render('joomla.content.info_block.block', array('item' => $this->item, 'params' => $params, 'position' => 'below')); ?>
		<?php endif; ?>
			<?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
				<?php $this->item->tagLayout = new JLayoutFile('joomla.content.tags'); ?>
				<?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
			<?php endif; ?>
	<?php endif; ?>

	<?php
if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative):
	echo $this->item->pagination;
?>
	<?php endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<?php // Optional teaser intro text for guests ?>
	<?php elseif ($params->get('show_noauth') == true && $user->get('guest')) : ?>
	<?php echo JLayoutHelper::render('joomla.content.intro_image', $this->item); ?>
	<?php echo JHtml::_('content.prepare', $this->item->introtext); ?>
	<?php //Optional link to let them register to see the whole article. ?>
	<?php if ($params->get('show_readmore') && $this->item->fulltext != null) : ?>
	<?php $menu = JFactory::getApplication()->getMenu(); ?>
	<?php $active = $menu->getActive(); ?>
	<?php $itemId = $active->id; ?>
	<?php $link = new JUri(JRoute::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
	<?php $link->setVar('return', base64_encode(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
	<p class="readmore">
		<a href="<?php echo $link; ?>" class="register">
		<?php $attribs = json_decode($this->item->attribs); ?>
		<?php
		if ($attribs->alternative_readmore == null) :
			echo JText::_('COM_CONTENT_REGISTER_TO_READ_MORE');
		elseif ($readmore = $attribs->alternative_readmore) :
			echo $readmore;
			if ($params->get('show_readmore_title', 0) != 0) :
				echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
			endif;
		elseif ($params->get('show_readmore_title', 0) == 0) :
			echo JText::sprintf('COM_CONTENT_READ_MORE_TITLE');
		else :
			echo JText::_('COM_CONTENT_READ_MORE');
			echo JHtml::_('string.truncate', $this->item->title, $params->get('readmore_limit'));
		endif; ?>
		</a>
	</p>
	<?php endif; ?>
	<?php endif; ?>
	<?php
if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
	echo $this->item->pagination;
?>
	<?php endif; ?>
	<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
	<?php echo $this->item->event->afterDisplayContent; ?>
</div>
